Fehlermeldung - `loc[,]` / `iloc[,]`
Im folgenden liegt uns eine Bücherliste names bookstore als csv-Datei vor. Diese beinhaltet gebrauchte Bücher mit entsprechend dazu kennzeichnenden Eigenschaften.

Über loc[,] bzw. iloc[,] ist es möglich sich einen gewünschten Teil/Ausschnitt eines DataFrames anzuschauen und einzelne Werte zu entnehmen.

Der folgende Code hat eine bestimmte Ausgabe als Ziel, jedoch weicht diese noch etwas von der Vorgabe ab. Passe den Code so an, dass er die gewünschte Ausgabe ausgibt.

Aufgabe 1:

Es sollen die Titel, Autoren und Verkaufspreise aller Bücher ausgegeben werden.

In [10]:
display(df.iloc[:, [0,1,3]])
# spalte 4 statt 3 wäre richtig

,Title,Author,List Price
0,The Lord of the Rings,"Tolkien, J.R.R.",7.99
1,The Bible,International Bible Society,7.50
2,The Pillars of the Earth,"Follett, Ken",19.95
3,Perfume: The Story of a Murderer,"Süskind, Patrick",19.95
4,The Little Prince,"Saint-Exupéry, Antoine de",24.95
5,Buddenbrooks,"Mann, Thomas",7.99
6,The Physician,"Gordon, Noah",25.95
7,The Alchemist,"Coelho, Paulo",7.50
8,Harry Potter and the Sorcerer’s Stone,"Rowling, J.K.",7.99
9,Pope Joan,"Cross, Donna W.",24.95
10,Inkheart,"Funke, Cornelia",9.99
11,Outlander,"Gabaldon, Diana",6.99
12,The House of the Spirits,"Allende, Isabel",7.99
13,The Reader,"Schlink, Bernhard",6.99
14,Faust,"Goethe, Johann Wolfgang von",7.50
15,The Shadow of the Wind,"Ruiz Zafón, Carlos",5.99
16,Pride and Prejudice,"Austen, Jane",6.99
17,The Name of the Rose,"Eco, Umberto",7.99
18,Angels & Demons,"Brown, Dan",5.95
19,Effi Briest,"Fontane, Theodor",19.95
20,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",7.99
21,The Magic Mountain,"Mann, Thomas",6.99
22,Gone with the Wind,"Mitchell, Margaret",6.50
23,Siddhartha,"Hesse, Hermann",7.99
24,The Discovery of Heaven,"Mulisch, Harry",7.99
25,The Neverending Story,"Ende, Michael",26.95
26,The Hidden Word,"Hahn, Ulla",6.99
27,Angela’s Ashes,"McCourt, Frank",24.95
28,Narcissus and Goldmund,"Hesse, Hermann",6.99
29,The Mists of Avalon,"Zimmer Bradley, Marion",5.99

Die Ausgabe ist momentan dahingehend nicht richtig, dass nicht der Verkaufspreis ausgegeben wird, sondern der Listenpreis. D.h. in der Spaltenangabe von iloc[,] müssen wir die Übergabe der 3. Spalte durch die 4. Spalte ersetzen.

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('bookstore.csv')

In [7]:
import pandas as pd

df = pd.read_csv("bookstore.csv")

display(df.iloc[:, [0,1,4]])

,Title,Author,Sale Price
0,The Lord of the Rings,"Tolkien, J.R.R.",2.69
1,The Bible,International Bible Society,2.49
2,The Pillars of the Earth,"Follett, Ken",1.49
3,Perfume: The Story of a Murderer,"Süskind, Patrick",1.29
4,The Little Prince,"Saint-Exupéry, Antoine de",2.59
5,Buddenbrooks,"Mann, Thomas",1.99
6,The Physician,"Gordon, Noah",1.29
7,The Alchemist,"Coelho, Paulo",1.29
8,Harry Potter and the Sorcerer’s Stone,"Rowling, J.K.",2.49
9,Pope Joan,"Cross, Donna W.",0.99
10,Inkheart,"Funke, Cornelia",0.99
11,Outlander,"Gabaldon, Diana",1.29
12,The House of the Spirits,"Allende, Isabel",1.49
13,The Reader,"Schlink, Bernhard",1.29
14,Faust,"Goethe, Johann Wolfgang von",2.49
15,The Shadow of the Wind,"Ruiz Zafón, Carlos",1.29
16,Pride and Prejudice,"Austen, Jane",1.29
17,The Name of the Rose,"Eco, Umberto",1.49
18,Angels & Demons,"Brown, Dan",1.29
19,Effi Briest,"Fontane, Theodor",1.29
20,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",1.99
21,The Magic Mountain,"Mann, Thomas",1.79
22,Gone with the Wind,"Mitchell, Margaret",1.29
23,Siddhartha,"Hesse, Hermann",1.99
24,The Discovery of Heaven,"Mulisch, Harry",1.29
25,The Neverending Story,"Ende, Michael",1.49
26,The Hidden Word,"Hahn, Ulla",1.29
27,Angela’s Ashes,"McCourt, Frank",1.29
28,Narcissus and Goldmund,"Hesse, Hermann",1.29
29,The Mists of Avalon,"Zimmer Bradley, Marion",1.29

Aufgabe 2:

Es sollen die ersten 4 Buchtitel ausgegeben werden

In [9]:
display(df.loc[:4, "Title"])

0               The Lord of the Rings
1                           The Bible
2            The Pillars of the Earth
3    Perfume: The Story of a Murderer
4                   The Little Prince
Name: Title, dtype: object

Aufgabe 2:

Momentan werden bei uns die ersten 5 Buchtitel ausgegeben, d.h. wir haben einen Fehler in den Zeilenangaben. Das Problem lässt sich schnell lösen, indem wir bei der Zeilenangabe die Angabe um eine Zeile reduziere

In [8]:
display(df.loc[:3, "Title"])

0               The Lord of the Rings
1                           The Bible
2            The Pillars of the Earth
3    Perfume: The Story of a Murderer
Name: Title, dtype: object